

version: 2

jobs:
  build:
    machine:
      # enabled: true
      image: circleci/classic:201808-01
    environment:
      GOPATH: /home/circleci/go
      # MINIKUBE_HOME: /home/circleci/go/src/github.com/pandorasNox/kubernetes-default-container-resources
      K8S_VERSION: "v1.12.0"
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v0.31.0
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
    working_directory: ~/go/src/github.com/pandorasNox/kubernetes-default-container-resources
    steps:
      # - restore_cache:
      #     name: restore tools cache
      #     keys:
      #       - tools-v6
      - checkout
      # - run:
      #     name: go test
      #     command: |
      #       make test
      # - run:
      #     name: lint go
      #     command: |
      #       make lint
      - run:
          name: setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - run:
          name: setup minikube
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          name: start minikube
          command: |
            sudo -E minikube start --vm-driver=none --cpus 1 --memory 2048 --kubernetes-version=${K8S_VERSION} &> $HOME/minikube.log 2>&1 < /dev/null
      - run:
          name: fix RBAC
          command: |
            # make default account cluster-admin
            kubectl create clusterrolebinding add-on-cluster-admin --clusterrole cluster-admin --serviceaccount=kube-system:default
      - run:
          name: dump cluster-info
          command: |
            kubectl cluster-info
      - run:
          name: wait for minikube
          command: |
            timeout 150 make ci-mini-await
      - run:
          name: dump running pods
          command: |
            kubectl get po --all-namespaces -o wide
      # - save_cache:
      #     name: save tools cache
      #     key: tools-v6
      #     paths:
      #       - kubectl
      #       - minikube
      #       - .minikube
      #       - docker-image-cache
      #       - .git
      #       - gometalinter
      - run:
          name: deploy draco (default-resources-admission-controller)
          command: |
            timeout 60 make deploy
      - run:
          name: logs draco (default-resources-admission-controller)
          background: true
          command: |
            kubectl -n mutating-webhook get po -o wide
            export DRACO_POD=$(kubectl -n mutating-webhook get po --template '{{range .items}}{{.metadata.name}}{{end}}')
            echo "start monitoring of ${DRACO_POD}"
            kubectl -n mutating-webhook logs ${DRACO_POD} -f
      - run:
          name: end-to-end test
          command: |
            # make end-to-end-test
            timeout 60 make bats
