
version: "2.3"
jobs:
  build:
    machine:
      enabled: true
      image: circleci/classic:201711-01
    environment:
      GOPATH: /home/circleci/go
      MINIKUBE_HOME: /home/circleci/go/src/github.com/pandorasNox/kubernetes-default-container-resources
    working_directory: ~/go/src/github.com/pandorasNox/kubernetes-default-container-resources
    steps:
      # - restore_cache:
      #     name: restore tools cache
      #     keys:
      #       - tools-v6
      - checkout
      - run:
          name: go test
          command: |
            make test
      - run:
          name: lint go
          command: |
            make lint
      - run:
          name: install kubectl & minikube
          command: |
            if [ ! -f kubectl ]; then
              curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.8.4/bin/linux/amd64/kubectl
            fi
            chmod +x kubectl
            sudo cp kubectl /usr/local/bin/
            if [ ! -f minikube ]; then
              curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v0.25.0/minikube-linux-amd64
            fi
            chmod +x minikube
            sudo cp minikube /usr/local/bin/
      - run:
          name: init minikube
          command: |
            make ci-mini-init
            sleep 65536
          background: true
      # - run:
      #     name: install go metalinter
      #     command: |
      #       if [ ! -d gometalinter ]; then
      #         mkdir gometalinter
      #         go get -u github.com/alecthomas/gometalinter
      #         $GOPATH/bin/gometalinter --install
      #         mv $GOPATH/bin/* gometalinter
      #       fi
      #       sudo cp gometalinter/* /usr/local/bin/
      # - run:
      #     name: preload docker imags
      #     command: |
      #       mkdir -p docker-image-cache
      #       cd docker-image-cache
      #       ../hack/docker-image.sh registry:2.6.2          registry-2.6.2
      #       ../hack/docker-image.sh docker:17.12.1-ce-dind  docker-17.12.1-ce-dind
      #       ../hack/docker-image.sh golang:1.10.0-alpine3.7 golang-1.10.0-alpine3.7
      #       ../hack/docker-image.sh alpine:3.7              alpine-3.7
      #       ../hack/docker-image.sh ubuntu:16.04            ubuntu-16.04
      - run:
          name: wait for minikube
          command: |
            make ci-mini-await
      # - save_cache:
      #     name: save tools cache
      #     key: tools-v6
      #     paths:
      #       - kubectl
      #       - minikube
      #       - .minikube
      #       - docker-image-cache
      #       - .git
      #       - gometalinter
      - run:
          name: deploy
          command: |
            timeout 60 make deploy
      - run:
          name: end-to-end test
          command: |
            # make end-to-end-test
            make bats
      # - run:
      #     name: queue test
      #     command: |
      #       make queue-test
      # - run:
      #     name: lint bash
      #     command: |
      #       sudo apt-get update
      #       sudo apt-get install shellcheck
      #       make lint-bash
