apiVersion: v1
kind: Pod
metadata:
  name: pod-with-wrong-resources
  namespace: foo
spec:
  containers:
  - image: nginx:1.7.9
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources:
      limits:
        memory: 256Mi
      requests:
        memory: 512Mi
